var kanjicards = [
{kanji: "政 ", word: " セイ ショウ マ  /  まつりごと ", meaning:" politics, government"},
{kanji: "議 ", word: "   /   ", meaning:" deliberation, consultation, debate, consideration"},
{kanji: "民 ", word: " ミン タ  /   ", meaning:" people, nation, subjects"},
{kanji: "連 ", word: " レン -ヅ.  /  つら.なる つら.ねる つ.れる ", meaning:" take along, lead, join, connect, party, gang, clique"},
{kanji: "対 ", word: " タイ ツイ ムカ.  /  あいて こた.える そろ.い つれあ.い なら.ぶ ", meaning:" vis-a-vis, opposite, even, equal, versus, anti-, compare"},
{kanji: "部 ", word: " ブ -  /   ", meaning:" section, bureau, dept, class, copy, part, portion, counter for copies of a newspaper or magazine"},
{kanji: "合 ", word: " ゴウ ガッ カッ -ア.ワセ  /  あ.う -あ.う あ.い あい- -あ.い -あい あ.わす あ.わせる ", meaning:" fit, suit, join"},
{kanji: "市 ", word: " シ イ  /   ", meaning:" market, city, town"},
{kanji: "内 ", word: " ナイ ダイ ウ  /   ", meaning:" inside, within, between, among, house, home"},
{kanji: "相 ", word: " ソウ ショウ  /  あい ", meaning:" inter-, mutual, together, each other, minister of state, councillor, aspect, phase, physiognomy"},
{kanji: "定 ", word: " テイ ジョウ サダ.  /  さだ.める さだ.まる ", meaning:" determine, fix, establish, decide"},
{kanji: "回 ", word: " カイ エ  /  まわ.る -まわ.る -まわ.り まわ.す -まわ.す まわ.し- -まわ.し もとお.る か.える ", meaning:" -times, round, game, revolve, counter for occurrences"},
{kanji: "選 ", word: " セン  /  えら.ぶ ", meaning:" elect, select, choose, prefer"},
{kanji: "米 ", word: " ベイ マイ メエトル ヨ  /  こめ ", meaning:" rice, USA, metre"},
{kanji: "実 ", word: " ジツ シツ ミチ.  /  み みの.る まこと まことに みの ", meaning:" reality, truth"},
{kanji: "関 ", word: " カン  /  せき -ぜき かか.わる からくり かんぬき ", meaning:" connection, barrier, gateway, involve, concerning"},
{kanji: "決 ", word: " ケツ  /  き.める -ぎ.め き.まる さ.く ", meaning:" decide, fix, agree upon, appoint"},
{kanji: "全 ", word: " ゼン スベ.  /  まった.く ", meaning:" whole, entire, all, complete, fulfill"},
{kanji: "表 ", word: " ヒョウ  /  おもて -おもて あらわ.す あらわ.れる あら.わす ", meaning:" surface, table, chart, diagram"},
{kanji: "戦 ", word: " セン ワナナ.  /  いくさ たたか.う おのの.く そよぐ ", meaning:" war, battle, match"},
{kanji: "経 ", word: " ケイ キョウ ノ  /  へ.る た.つ たていと はか.る ", meaning:" sutra, longitude, pass thru, expire, warp"},
{kanji: "最 ", word: " サイ シュ ツ  /  もっと.も ", meaning:" utmost, most, extreme"},
{kanji: "現 ", word: " ゲン アラワ.  /  あらわ.れる ", meaning:" present, existing, actual"},
{kanji: "調 ", word: " チョウ トトノ.エ  /  しら.べる しら.べ ととの.う ", meaning:" tune, tone, meter, key (music), writing style, prepare, exorcise, investigate"},
{kanji: "化 ", word: " カ ケ  /  ば.ける ば.かす ふ.ける け.する ", meaning:" change, take the form of, influence, enchant, delude, -ization"},
{kanji: "当 ", word: " トウ マサ.ニベ  /  あ.たる あ.たり あ.てる あ.て まさ.に ", meaning:" hit, right, appropriate, himself"},
{kanji: "約 ", word: " ヤク  /   ", meaning:" promise, approximately, shrink"},
{kanji: "首 ", word: " シュ ク  /   ", meaning:" neck"},
{kanji: "法 ", word: " ホウ ハッ ホッ フラン ノ  /   ", meaning:" method, law, rule, principle, model, system"},
{kanji: "性 ", word: " セイ ショウ  /  さが ", meaning:" sex, gender, nature"},
{kanji: "要 ", word: " ヨウ イ.  /   ", meaning:" need, main point, essence, pivot, key to"},
{kanji: "制 ", word: " セイ  /   ", meaning:" system, law, rule"},
{kanji: "治 ", word: " ジ チ ナオ.  /  おさ.める おさ.まる なお.る ", meaning:" reign, be at peace, calm down, subdue, quell, govt, cure, heal, rule, conserve"},
{kanji: "務 ", word: " ム ツト.メ  /   ", meaning:" task, duties"},
{kanji: "成 ", word: " セイ ジョウ -ナ.  /  な.る な.す ", meaning:" turn into, become, get, grow, elapse, reach"},
{kanji: "期 ", word: " キ ゴ  /   ", meaning:" period, time, date, term"},
{kanji: "取 ", word: " シュ -ド.  /  と.る と.り と.り- とり ", meaning:" take, fetch, take up"},
{kanji: "都 ", word: " ト ツ ミヤ  /   ", meaning:" metropolis, capital"},
{kanji: "和 ", word: " ワ オ カ ナゴ.ヤ  /  やわ.らぐ やわ.らげる なご.む ", meaning:" harmony, Japanese style, peace, soften, Japan"},
{kanji: "機 ", word: " キ  /  はた ", meaning:" mechanism, opportunity, occasion, machine, airplane"},
{kanji: "平 ", word: " ヘイ ビョウ ヒョウ  /  たい.ら -だいら ひら ひら ", meaning:" even, flat, peace"},
{kanji: "加 ", word: " カ  /  くわ.える くわ.わる ", meaning:" add, addition, increase, join, include, Canada"},
{kanji: "受 ", word: " ジュ ウ.カ  /  う.ける -う.け ", meaning:" accept, undergo, answer (phone), take, get, catch, receive"},
{kanji: "続 ", word: " ゾク ショク コウ キョウ ツグ.ナ  /  つづ.く つづ.ける ", meaning:" continue, series, sequel"},
{kanji: "進 ", word: " シン スス.メ  /  すす.む ", meaning:" advance, proceed, progress, promote"},
{kanji: "数 ", word: " スウ ス サク ソク シュ ワズラワ.シ  /  かず かぞ.える しばしば せ.める ", meaning:" number, strength, fate, law, figures"},
{kanji: "記 ", word: " キ シル.  /   ", meaning:" scribe, account, narrative"},
{kanji: "初 ", word: " ショ -ゾ.  /  はじ.め はじ.めて はつ はつ- うい- -そ.める ", meaning:" first time, beginning"},
{kanji: "指 ", word: " シ -サ.  /  ゆび さ.す ", meaning:" finger, point to, indicate, put into, play (chess), measure (ruler)"},
{kanji: "権 ", word: " ケン ゴン  /  おもり かり はか.る ", meaning:" authority, power, rights"},
{kanji: "支 ", word: "   /  しんよう じゅうまた ", meaning:" branch, support, sustain"},
{kanji: "産 ", word: " サン ム.  /  う.む う.まれる うぶ- ", meaning:" products, bear, give birth, yield, childbirth, native, property"},
{kanji: "点 ", word: " テン  /  つ.ける つ.く た.てる さ.す とぼ.す とも.す ぼち ", meaning:" spot, point, mark, speck, decimal point"},
{kanji: "報 ", word: " ホウ  /  むく.いる ", meaning:" report, news, reward, retribution"},
{kanji: "済 ", word: " サイ セイ ワタ.  /  す.む -ず.み -ずみ す.まない す.ます -す.ます すく.う な.す わたし ", meaning:" finish, come to an end, excusable, need not"},
{kanji: "活 ", word: " カツ  /  い.きる い.かす い.ける ", meaning:" lively, resuscitation, being helped, living"},
{kanji: "原 ", word: " ゲン ハ  /   ", meaning:" meadow, original, primitive, field, plain, prairie, tundra, wilderness"},
{kanji: "共 ", word: " キョウ  /  とも とも.に -ども ", meaning:" together, both, neither, all, and, alike, with"},
{kanji: "得 ", word: " トク ウ.  /  え.る ", meaning:" gain, get, find, earn, acquire, can, may, able to, profit, advantage, benefit"},
{kanji: "解 ", word: " カイ ゲ サト.  /  と.く と.かす と.ける ほど.く ほど.ける わか.る ", meaning:" unravel, notes, key, explanation, understanding, untie, undo, solve, answer, cancel, absolve, explain, minute"},
{kanji: "交 ", word: " コウ コモゴ  /  まじ.わる まじ.える ま.じる まじ.る ま.ざる ま.ぜる -か.う か.わす かわ.す ", meaning:" mingle, mixing, association, coming & going"},
{kanji: "資 ", word: "   /   ", meaning:" assets, resources, capital, funds, data, be conducive to, contribute to"},
{kanji: "予 ", word: " ヨ シャ  /  あらかじ.め ", meaning:" beforehand, previous, myself, I"},
{kanji: "向 ", word: " コウ ムカ.  /  む.く む.い -む.き む.ける -む.け む.かう む.かい む.こう む.こう- むこ ", meaning:" yonder, facing, beyond, confront, defy, tend toward, approach"},
{kanji: "際 ", word: " サイ -ギ  /  きわ ", meaning:" occasion, side, edge, verge, dangerous, adventurous, indecent, time, when"},
{kanji: "勝 ", word: " ショウ カ  /  か.つ -が.ち まさ.る すぐ.れる ", meaning:" victory, win, prevail, excel"},
{kanji: "面 ", word: " メン ベン ツ  /  おも おもて ", meaning:" mask, face, features, surface"},
{kanji: "告 ", word: " コク ツ.ゲ  /   ", meaning:" revelation, tell, inform, announce"},
{kanji: "反 ", word: " ハン ホン タン ホ -カエ.  /  そ.る そ.らす かえ.す かえ.る ", meaning:" anti-"},
{kanji: "判 ", word: " ハン バン  /  わか.る ", meaning:" judgement, signature, stamp, seal"},
{kanji: "認 ", word: " ニン  /  みと.める したた.める ", meaning:" acknowledge, witness, discern, recognize, appreciate, believe"},
{kanji: "参 ", word: " サン シン ミ  /  まい.る まい- まじわる ", meaning:" nonplussed, three, going, coming, visiting, visit, be defeated, die, be madly in love"},
{kanji: "利 ", word: " リ キ.  /   ", meaning:" profit, advantage, benefit"},
{kanji: "組 ", word: " ソ  /  く.む くみ -ぐみ ", meaning:" association, braid, plait, construct, assemble, unite, cooperate, grapple"},
{kanji: "信 ", word: " シ  /   ", meaning:" faith, truth, fidelity, trust"},
{kanji: "在 ", word: " ザイ ア.  /   ", meaning:" exist, outskirts, suburbs, located in"},
{kanji: "件 ", word: " ケン  /  くだん ", meaning:" affair, case, matter, item"},
{kanji: "側 ", word: " ソク  /  かわ がわ そば ", meaning:" side, lean, oppose, regret"},
{kanji: "任 ", word: " ニン マカ.  /  まか.せる ", meaning:" responsibility, duty, term, entrust to, appoint"},
{kanji: "引 ", word: " イン ヒ.ケ  /  ひ.く ひ.き ひ.き- -び.き ", meaning:" pull, tug, jerk, admit, install, quote, refer to"},
{kanji: "求 ", word: " キュウ グ  /  もと.める ", meaning:" request, want, wish for, require, demand"},
{kanji: "所 ", word: " ショ ト  /  ところ -ところ どころ ", meaning:" place"},
{kanji: "次 ", word: " ジ シ ツ  /  つ.ぐ ", meaning:" next, order, sequence"},
{kanji: "昨 ", word: " サク  /   ", meaning:" yesterday, previous"},
{kanji: "論 ", word: " ロン  /   ", meaning:" argument, discourse"},
{kanji: "官 ", word: " カン  /   ", meaning:" bureaucrat, the government"},
{kanji: "増 ", word: " ゾウ フ.ヤ  /  ま.す ま.し ふ.える ", meaning:" increase, add, augment, gain, promote"},
{kanji: "係 ", word: " ケイ  /  かか.る かかり -がかり かか.わる ", meaning:" person in charge, connection, duty, concern oneself"},
{kanji: "感 ", word: " カン  /   ", meaning:" emotion, feeling, sensation"},
{kanji: "情 ", word: " ジョウ セイ  /  なさ.け ", meaning:" feelings, emotion, passion, sympathy, circumstances, facts"},
{kanji: "投 ", word: " トウ  /  な.げる -な.げ ", meaning:" throw, discard, abandon, launch into, join, invest in, hurl, give up, sell at a loss"},
{kanji: "示 ", word: " ジ シ  /  しめ.す ", meaning:" show, indicate, point out, express, display"},
{kanji: "変 ", word: " ヘン  /  か.わる か.わり か.える ", meaning:" unusual, change, strange"},
{kanji: "打 ", word: " ダ ダアス ブ.  /  う.つ う.ち- ", meaning:" strike, hit, knock, pound, dozen"},
{kanji: "直 ", word: " チョク ジキ ジカ ス.  /  ただ.ちに なお.す -なお.す なお.る なお.き ", meaning:" straightaway, honesty, frankness, fix, repair"},
{kanji: "両 ", word: " リョウ フタ  /  てる ", meaning:" both, old Japanese coin, counter for vehicles, two"},
{kanji: "式 ", word: " シ  /   ", meaning:" style, ceremony, rite, function, method, system, form, expression"},
{kanji: "確 ", word: " カク コウ  /  たし.か たし.かめる ", meaning:" assurance, firm, tight, hard, solid, confirm, clear, evident"},
{kanji: "果 ", word: " カ ハ.  /  は.たす はた.す -は.たす は.てる -は.てる ", meaning:" fruit, reward, carry out, achieve, complete, end, finish, succeed"},
{kanji: "容 ", word: " ヨウ イ.レ  /   ", meaning:" contain, form, looks"},
{kanji: "必 ", word: " ヒツ  /  かなら.ず ", meaning:" invariably, certain, inevitable"},
{kanji: "演 ", word: " エン  /   ", meaning:" performance, act, play, render, stage"},
{kanji: "歳 ", word: " サイ セイ  /  とし とせ よわい ", meaning:" year-end, age, occasion, opportunity"},
{kanji: "争 ", word: " ソウ  /  あらそ.う いか.でか ", meaning:" contend, dispute, argue"},
{kanji: "談 ", word: " ダン  /   ", meaning:" discuss, talk"},
{kanji: "能 ", word: " ノウ ヨ.  /   ", meaning:" ability, talent, skill, capacity"},
{kanji: "位 ", word: " イ グラ  /  くらい ", meaning:" rank, grade, throne, crown, about, some"},
{kanji: "置 ", word: " チ -オ.  /  お.く ", meaning:" placement, put, set, deposit, leave behind, keep, employ, pawn"},
{kanji: "流 ", word: " リュウ ル -ナガ.  /  なが.れる なが.れ なが.す ", meaning:" current, a sink, flow, forfeit"},
{kanji: "格 ", word: " カク コウ キャク ゴ  /   ", meaning:" status, rank, capacity, character, case (law,  grammar)"},
{kanji: "疑 ", word: " ギ  /  うたが.う ", meaning:" doubt, distrust, be suspicious, question"},
{kanji: "過 ", word: " カ  /  す.ぎる -す.ぎる -す.ぎ す.ごす あやま.つ あやま.ち ", meaning:" overdo, exceed, go beyond, error"},
{kanji: "局 ", word: " キョク  /  つぼね ", meaning:" bureau, board, office, affair, conclusion, court lady, lady-in-waiting, her apartment"},
{kanji: "放 ", word: " ホウ ホウ.  /  はな.す -っぱな.し はな.つ はな.れる こ.く ", meaning:" set free, release, fire, shoot, emit, banish, liberate"},
{kanji: "常 ", word: " ジョウ  /  つね とこ ", meaning:" usual, ordinary, normal, regular"},
{kanji: "状 ", word: " ジョウ  /   ", meaning:" status quo, conditions, circumstances, form, appearance"},
{kanji: "球 ", word: " キュウ タ  /   ", meaning:" ball, sphere"},
{kanji: "職 ", word: " ショク ソ  /   ", meaning:" post, employment, work"},
{kanji: "与 ", word: " ヨ トモ  /  あた.える あずか.る くみ.する ", meaning:" bestow, participate in, give, award, impart, provide, cause, gift, godsend"},
{kanji: "供 ", word: " キョウ ク クウ グ  /  そな.える とも -ども ", meaning:" submit, offer, present, serve (meal), accompany"},
{kanji: "役 ", word: " ヤク エ  /   ", meaning:" duty, war, campaign, drafted labor, office, service, role"},
{kanji: "構 ", word: " コウ カマ.  /  かま.える ", meaning:" posture, build, pretend"},
{kanji: "割 ", word: " カツ  /  わ.る わり わ.り わ.れる さ.く ", meaning:" proportion, comparatively, divide, cut, separate, split"},
{kanji: "費 ", word: " ヒ  /  つい.やす つい.える ", meaning:" expense, cost, spend, consume, waste"},
{kanji: "付 ", word: " フ -ヅ  /  つ.ける -つ.ける -づ.ける つ.け つ.け- -つ.け -づ.け -づけ つ.く -づ.く つ.き -つ.き -つ ", meaning:" adhere, attach, refer to, append"},
{kanji: "由 ", word: " ユ ユウ ユイ  /  よし よ.る ", meaning:" wherefore, a reason"},
{kanji: "説 ", word: " セツ ゼイ ト.  /   ", meaning:" rumor, opinion, theory"},
{kanji: "難 ", word: " ナン -ニク.  /  かた.い -がた.い むずか.しい むづか.しい むつか.しい ", meaning:" difficult, impossible, trouble, accident, defect"},
{kanji: "優 ", word: " ユウ ウ マサ.  /  やさ.しい すぐ.れる ", meaning:" tenderness, excel, surpass, actor, superiority, gentleness"},
{kanji: "夫 ", word: " フ フウ ブ ソ.  /  おっと ", meaning:" husband, man"},
{kanji: "収 ", word: " シュウ オサ.マ  /  おさ.める ", meaning:" income, obtain, reap, pay, supply, store"},
{kanji: "断 ", word: " ダン  /  た.つ ことわ.る さだ.める ", meaning:" severance, decline, refuse, apologize, warn, dismiss, prohibit, decision, judgement, cutting"},
{kanji: "石 ", word: " セキ シャク コク イ  /   ", meaning:" stone"},
{kanji: "違 ", word: " イ  /  ちが.う ちが.い ちが.える -ちが.える たが.う たが.える ", meaning:" difference, differ"},
{kanji: "消 ", word: " ショウ  /  き.える け.す ", meaning:" extinguish, blow out, turn off, neutralize, cancel"},
{kanji: "神 ", word: " シン ジン  /  かみ かん- こう ", meaning:" gods, mind, soul"},
{kanji: "番 ", word: " バン ツガ.  /   ", meaning:" turn, number in a series"},
{kanji: "規 ", word: "   /   ", meaning:" standard, measure"},
{kanji: "術 ", word: " ジュツ  /  すべ ", meaning:" art, technique, skill, means, trick, resources, magic"},
{kanji: "備 ", word: " ビ ツブサ.  /  そな.える そな.わる ", meaning:" equip, provision, preparation"},
{kanji: "宅 ", word: " タ  /   ", meaning:" home, house, residence, our house, my husband"},
{kanji: "害 ", word: " ガイ  /   ", meaning:" harm, injury"},
{kanji: "配 ", word: " ハイ  /  くば.る ", meaning:" distribute, spouse, exile, rationing"},
{kanji: "警 ", word: " ケイ  /  いまし.める ", meaning:" admonish, commandment"},
{kanji: "育 ", word: " イク ハグク.  /  そだ.つ そだ.ち そだ.てる ", meaning:" bring up, grow up, raise, rear"},
{kanji: "席 ", word: " セキ  /  むしろ ", meaning:" seat, mat, occasion, place"},
{kanji: "訪 ", word: " ホウ ト.  /  おとず.れる たず.ねる ", meaning:" call on, visit, look up, offer sympathy"},
{kanji: "乗 ", word: " ジョウ ショウ ノ.セ  /  の.る -の.り ", meaning:" ride, power, multiplication, record, counter for vehicles, board, mount, join"},
{kanji: "残 ", word: " ザン サン  /  のこ.る のこ.す そこな.う のこ.り ", meaning:" remainder, leftover, balance"},
{kanji: "想 ", word: " ソウ ソ  /  おも.う ", meaning:" concept, think, idea, thought"},
{kanji: "声 ", word: " セイ ショウ  /  こえ こわ- ", meaning:" voice"},
{kanji: "念 ", word: " ネン  /   ", meaning:" wish, sense, idea, thought, feeling, desire, attention"},
{kanji: "助 ", word: " ジョ  /  たす.ける たす.かる す.ける すけ ", meaning:" help, rescue, assist"},
{kanji: "労 ", word: " ロウ  /  ろう.する いたわ.る いた.ずき ねぎら つか.れる ねぎら.う ", meaning:" labor, thank for, reward for, toil, trouble"},
{kanji: "例 ", word: " レイ  /  たと.える ", meaning:" example, custom, usage, precedent"},
{kanji: "然 ", word: " ゼン ネン  /  しか しか.り しか.し さ ", meaning:" sort of thing, so, if so, in that case, well"},
{kanji: "限 ", word: " ゲン  /  かぎ.る かぎ.り -かぎ.り ", meaning:" limit, restrict, to best of ability"},
{kanji: "追 ", word: " ツイ オ.  /   ", meaning:" chase, drive away, follow, pursue, meanwhile"},
{kanji: "商 ", word: " ショウ アキナ.  /   ", meaning:" make a deal, selling, dealing in, merchant"},
{kanji: "葉 ", word: " ヨウ   /   ", meaning:" leaf, plane, lobe, needle, blade, spear, counter for flat things, fragment, piece"},
{kanji: "伝 ", word: " デン テン ツ  /  つた.わる つた.える つた.う つだ.う -づた.い ", meaning:" transmit, go along, walk along, follow, report, communicate, legend, tradition"},
{kanji: "働 ", word: " ドウ リュク リキ ロク リョク  /  はたら.く ", meaning:" work, (kokuji)"},
{kanji: "形 ", word: " ケイ ギョウ ナ  /  かた -がた かたち ", meaning:" shape, form, style"},
{kanji: "景 ", word: " ケ  /   ", meaning:" scenery, view"},
{kanji: "落 ", word: " ラク オ.ト  /  お.ちる お.ち ", meaning:" fall, drop, come down"},
{kanji: "好 ", word: " コウ イ.  /  この.む す.く よ.い ", meaning:" fond, pleasing, like something"},
{kanji: "退 ", word: " タイ  /  しりぞ.く しりぞ.ける ひ.く の.く の.ける ど.く ", meaning:" retreat, withdraw, retire, resign, repel, expel, reject"},
{kanji: "頭 ", word: " トウ ズ ト カブ  /  あたま かしら -がしら ", meaning:" head, counter for large animals"},
{kanji: "負 ", word: " フ  /  ま.ける ま.かす お.う ", meaning:" defeat, negative, -, minus, bear, owe, assume a responsibility"},
{kanji: "渡 ", word: " ト ワタ.  /  わた.る -わた.る ", meaning:" transit, ford, ferry, cross, import, deliver, diameter, migrate"},
{kanji: "失 ", word: " シツ  /  うしな.う う.せる ", meaning:" lose, error, fault, disadvantage, loss"},
{kanji: "差 ", word: " サ  /  さ.す さ.し ", meaning:" distinction, difference, variation, discrepancy, margin, balance"},
{kanji: "末 ", word: " マツ バツ  /  すえ ", meaning:" end, close, tip, powder, posterity"},
{kanji: "守 ", word: " シュ ス カ  /  まも.る まも.り もり -もり ", meaning:" guard, protect, defend, obey"},
{kanji: "若 ", word: " ジャク ニャク ニャ モ.シク  /  わか.い わか- も.しくわ も.し ", meaning:" young, if, perhaps, possibly, low number, immature"},
{kanji: "種 ", word: " シュ -グ  /  たね ", meaning:" species, kind, class, variety, seed"},
{kanji: "美 ", word: " ビ ミ ウツク.シ  /   ", meaning:" beauty, beautiful"},
{kanji: "命 ", word: " メイ ミョウ  /  いのち ", meaning:" fate, command, decree, destiny, life, appoint"},
{kanji: "福 ", word: " フ  /   ", meaning:" blessing, fortune, luck, wealth"},
{kanji: "望 ", word: " ボウ モウ モ  /  のぞ.む ", meaning:" ambition, full moon, hope, desire, aspire to, expect"},
{kanji: "非 ", word: " ヒ  /  あら.ず ", meaning:" un-, mistake, negative, injustice, non-"},
{kanji: "観 ", word: " カン  /  み.る しめ.す ", meaning:" outlook, look, appearance, condition, view"},
{kanji: "察 ", word: " サツ  /   ", meaning:" guess, presume, surmise, judge, understand"},
{kanji: "段 ", word: " ダン タン  /   ", meaning:" grade, steps, stairs"},
{kanji: "横 ", word: " オウ  /  よこ ", meaning:" sideways, side, horizontal, width, woof"},
{kanji: "深 ", word: " シン  /  ふか.い -ぶか.い ふか.まる ふか.める み- ", meaning:" deep, heighten, intensify, strengthen"},
{kanji: "申 ", word: " シン  /  もう.す もう.し- さる ", meaning:" have the honor to, sign of the monkey, 3-5PM, ninth sign of Chinese zodiac"},
{kanji: "様 ", word: " ヨウ ショウ  /  さま さん ", meaning:" Esq., way, manner, situation, polite suffix"},
{kanji: "財 ", word: " ザイ サイ ゾ  /   ", meaning:" property, money, wealth, assets"},
{kanji: "港 ", word: " コウ  /  みなと ", meaning:" harbor"},
{kanji: "識 ", word: " シ  /   ", meaning:" discriminating, know, write"},
{kanji: "呼 ", word: " コ ヨ.  /   ", meaning:" call, call out to, invite"},
{kanji: "達 ", word: " タツ ダ -タ  /   ", meaning:" accomplished, reach, arrive, attain"},
{kanji: "良 ", word: " リョウ -イ.  /  よ.い -よ.い い.い ", meaning:" good, pleasing, skilled"},
{kanji: "候 ", word: " コウ  /  そうろう ", meaning:" climate, season, weather"},
{kanji: "程 ", word: " テイ -ホ  /  ほど ", meaning:" extent, degree, law, formula, distance, limits, amount"},
{kanji: "満 ", word: " マン バン ミ.タ  /  み.ちる み.つ ", meaning:" full, enough, pride, satisfy"},
{kanji: "敗 ", word: " ハイ  /  やぶ.れる ", meaning:" failure, defeat, reversal"},
{kanji: "値 ", word: " チ アタ  /  ね ", meaning:" price, cost, value"},
{kanji: "突 ", word: " トツ カ  /  つ.く ", meaning:" stab, protruding, thrusting, thrust, pierce, prick"},
{kanji: "光 ", word: " コウ ヒカ  /  ひか.る ", meaning:" ray, light"},
{kanji: "路 ", word: " ロ ル  /  -じ みち ", meaning:" path, route, road, distance"},
{kanji: "科 ", word: "   /   ", meaning:" department, course, section"},
{kanji: "積 ", word: " セキ ツ.モ  /  つ.む -づ.み つ.もる ", meaning:" volume, product (x*y), acreage, contents, pile up, stack, load, amass"},
{kanji: "他 ", word: " タ  /  ほか ", meaning:" other, another, the others"},
{kanji: "処 ", word: " ショ  /  ところ -こ お.る ", meaning:" dispose, manage, deal with, sentence, condemn, act, behave, place"},
{kanji: "太 ", word: " タイ タ フト.  /  ふと.い ", meaning:" plump, thick, big around"},
{kanji: "客 ", word: " キャク カク  /   ", meaning:" guest, visitor, customer, client"},
{kanji: "否 ", word: " ヒ  /  いな いや ", meaning:" negate, no, noes, refuse, decline, deny"},
{kanji: "師 ", word: "   /   ", meaning:" expert, teacher, master, army, war"},
{kanji: "登 ", word: " トウ ト ドウ ショウ チョウ ア.ガ  /  のぼ.る ", meaning:" ascend, climb up"},
{kanji: "易 ", word: " エキ イ  /  やさ.しい やす.い ", meaning:" easy, ready to, simple, fortune-telling, divination"},
{kanji: "速 ", word: " ソク スミ.ヤ  /  はや.い はや- はや.める ", meaning:" quick, fast"},
{kanji: "存 ", word: " ソン ゾ  /   ", meaning:" suppose, be aware of, believe, feel"},
{kanji: "飛 ", word: " ヒ -ト.バ  /  と.ぶ と.ばす ", meaning:" fly, skip (pages), scatter"},
{kanji: "殺 ", word: " サツ サイ セツ  /  ころ.す -ごろ.し そ.ぐ ", meaning:" kill, murder, butcher, slice off, split, diminish, reduce, spoil"},
{kanji: "号 ", word: " ゴウ  /  さけ.ぶ よびな ", meaning:" nickname, number, item, title, pseudonym, name, call"},
{kanji: "単 ", word: " タン  /  ひとえ ", meaning:" simple, one, single, merely"},
{kanji: "座 ", word: " ザ  /  すわ.る ", meaning:" squat, seat, cushion, gathering, sit"},
{kanji: "破 ", word: " ハ ヤブ.レ  /  やぶ.る ", meaning:" rend, rip, tear, break, destroy, defeat, frustrate"},
{kanji: "除 ", word: " ジョ ジ  /  のぞ.く -よ.け ", meaning:" exclude, division (x, 3), remove, abolish, cancel, except"},
{kanji: "完 ", word: " カン  /   ", meaning:" perfect, completion, end"},
{kanji: "降 ", word: " コウ ゴ クダ.  /  お.りる お.ろす ふ.る ふ.り くだ.る ", meaning:" descend, precipitate, fall, surrender"},
{kanji: "責 ", word: " セキ  /  せ.める ", meaning:" blame, condemn, censure"},
{kanji: "捕 ", word: " ホ  /  と.らえる と.らわれる と.る とら.える とら.われる つか.まえる つか.まる ", meaning:" catch, capture"},
{kanji: "危 ", word: " キ  /  あぶ.ない あや.うい あや.ぶむ ", meaning:" dangerous, fear, uneasy"},
{kanji: "給 ", word: " キュウ -タマ.  /  たま.う たも.う ", meaning:" salary, wage, gift, allow, grant, bestow on"},
{kanji: "苦 ", word: " ク  /  くる.しい -ぐる.しい くる.しむ くる.しめる にが.い にが.る ", meaning:" suffering, trial, worry, hardship, feel bitter, scowl"},
{kanji: "迎 ", word: " ゲイ ムカ.エ  /   ", meaning:" welcome, meet, greet"},
{kanji: "園 ", word: " エン ソ  /   ", meaning:" park, garden, yard, farm"},
{kanji: "具 ", word: " グ ツブサ.  /  そな.える ", meaning:" tool, utensil, means, possess, ingredients, counter for armor,  suits,  sets of furniture"},
{kanji: "辞 ", word: " ジ  /  や.める いな.む ", meaning:" resign, word, term, expression"},
{kanji: "因 ", word: " イン チナ.  /  よ.る ", meaning:" cause, factor, be associated with, depend on, be limited to"},
{kanji: "馬 ", word: " バ   /  うま うま- ", meaning:" horse"},
{kanji: "愛 ", word: " アイ イト.シ  /   ", meaning:" love, affection, favourite"},
{kanji: "富 ", word: " フ フウ ト  /  と.む ", meaning:" wealth, enrich, abundant"},
{kanji: "彼 ", word: " ヒ カ.  /  かれ かの ", meaning:" he, that, the"},
{kanji: "未 ", word: " ミ ビ  /  いま.だ ま.だ ひつじ ", meaning:" un-, not yet, hitherto, still, even now, sign of the ram, 1-3PM, eighth sign of Chinese zodiac"},
{kanji: "舞 ", word: " ブ  /  ま.う -ま.う まい ", meaning:" dance, flit, circle, wheel"},
{kanji: "亡 ", word: " ボウ モウ  /  な.い な.き- ほろ.びる ほろ.ぶ ほろ.ぼす ", meaning:" deceased, the late, dying, perish"},
{kanji: "冷 ", word: " レイ  /  つめ.たい ひ.える ひ.や ひ.ややか ひ.やす ひ.やかす さ.める さ.ます ", meaning:" cool, cold (beer,  person), chill"},
{kanji: "適 ", word: " テキ  /  かな.う ", meaning:" suitable, occasional, rare, qualified, capable"},
{kanji: "婦 ", word: "   /   ", meaning:" lady, woman, wife, bride"},
{kanji: "寄 ", word: " キ ヨ.セ  /  よ.る -よ.り ", meaning:" draw near, stop in, bring near, gather, collect, send, forward"},
{kanji: "込 ", word: " コ.メ  /  -こ.む こ.む こ.み -こ.み ", meaning:" crowded, mixture, in bulk, included, (kokuji)"},
{kanji: "顔 ", word: " ガン  /  かお ", meaning:" face, expression"},
{kanji: "類 ", word: " ルイ  /  たぐ.い ", meaning:" sort, kind, variety, class, genus"},
{kanji: "余 ", word: " ヨ アマ.  /  あま.る あま.り ", meaning:" too much, myself, surplus, other, remainder"},
{kanji: "王 ", word: " オウ -ノ  /   ", meaning:" king, rule, magnate"},
{kanji: "返 ", word: " ヘン  /  かえ.す -かえ.す かえ.る -かえ.る ", meaning:" return, answer, fade, repay"},
{kanji: "妻 ", word: " サイ ツ  /   ", meaning:" wife, spouse"},
{kanji: "背 ", word: " ハイ  /  せ せい そむ.く そむ.ける ", meaning:" stature, height, back, behind, disobey, defy, go back on, rebel"},
{kanji: "熱 ", word: " ネツ アツ.  /   ", meaning:" heat, temperature, fever, mania, passion"},
{kanji: "宿 ", word: " シュク ヤド.  /  やど やど.る ", meaning:" inn, lodging, relay station, dwell, lodge, be pregnant, home, dwelling"},
{kanji: "薬 ", word: " ヤク クス  /   ", meaning:" medicine, chemical, enamel, gunpowder, benefit"},
{kanji: "険 ", word: " ケン  /  けわ.しい ", meaning:" precipitous, inaccessible place, impregnable position, steep place, sharp eyes"},
{kanji: "頼 ", word: " ライ タヨ.  /  たの.む たの.もしい ", meaning:" trust, request"},
{kanji: "覚 ", word: " カク  /  おぼ.える さ.ます さ.める さと.る ", meaning:" memorize, learn, remember, awake, sober up"},
{kanji: "船 ", word: " セン  /  ふね ふな ", meaning:" ship, boat"},
{kanji: "途 ", word: "   /   ", meaning:" route, way, road"},
{kanji: "許 ", word: " キョ  /  ゆる.す もと ", meaning:" permit, approve"},
{kanji: "抜 ", word: " バツ ハツ ハイ ヌ.カ  /  ぬ.く -ぬ.く ぬ.き ぬ.ける ぬ.かす ", meaning:" slip out, extract, pull out, pilfer, quote, remove, omit"},
{kanji: "便 ", word: " ベン ビン  /  たよ.り ", meaning:" convenience"},
{kanji: "留 ", word: " リュウ ル ルウブ  /  と.める と.まる とど.める とど.まる ", meaning:" detain, fasten, halt, stop"},
{kanji: "罪 ", word: " ザイ  /  つみ ", meaning:" guilt, sin, crime, fault, blame, offense"},
{kanji: "努 ", word: " ド  /  つと.める ", meaning:" toil, diligent, as much as possible"},
{kanji: "精 ", word: " セイ ショウ シヤ  /   ", meaning:" refined, ghost, fairy, energy, vitality, semen, excellence, purity, skill"},
{kanji: "散 ", word: " サン バ  /  ち.る ち.らす -ち.らす ち.らかす ち.らかる ", meaning:" scatter, disperse, spend, squander"},
{kanji: "静 ", word: " セイ ジョウ シズ.メ  /  しず- しず.か しず.まる ", meaning:" quiet"},
{kanji: "婚 ", word: " コン  /   ", meaning:" marriage"},
{kanji: "喜 ", word: " キ ヨロコ.バ  /  よろこ.ぶ ", meaning:" rejoice, take pleasure in"},
{kanji: "浮 ", word: " フ ウ.カベ  /  う.く う.かれる う.かぶ む ", meaning:" floating, float, rise to surface"},
{kanji: "絶 ", word: " ゼツ  /  た.える た.やす た.つ ", meaning:" discontinue, beyond, sever, cut off, abstain, interrupt, suppress"},
{kanji: "幸 ", word: " コウ シアワ.  /  さいわ.い さち ", meaning:" happiness, blessing, fortune"},
{kanji: "押 ", word: " オウ オサ.エ  /  お.す お.し- お.っ- お.さえる ", meaning:" push, stop, check, subdue, attach, seize, weight, shove, press, seal, do in spite of"},
{kanji: "倒 ", word: " トウ  /  たお.れる -だお.れ たお.す ", meaning:" overthrow, fall, collapse, drop, break down"},
{kanji: "等 ", word: " トウ -  /  ひと.しい など ", meaning:" etc., and so forth, class (first), quality, equal, similar"},
{kanji: "老 ", word: " ロウ フ.ケ  /  お.いる ", meaning:" old man, old age, grow old"},
{kanji: "曲 ", word: " キョク マ.ゲ  /  ま.がる ", meaning:" bend, music, melody, composition, pleasure, injustice, fault, curve, crooked, perverse, lean"},
{kanji: "払 ", word: " フツ ヒツ ホツ -バラ.  /  はら.う -はら.い ", meaning:" pay, clear out, prune, banish, dispose of"},
{kanji: "庭 ", word: " テイ ニ  /   ", meaning:" courtyard, garden, yard"},
{kanji: "徒 ", word: " ト ア  /  いたずら ", meaning:" junior, emptiness, vanity, futility, uselessness, ephemeral thing, gang, set, party, people"},
{kanji: "勤 ", word: " キン ゴン  /  つと.める -づと.め つと.まる いそ.しむ ", meaning:" diligence, become employed, serve"},
{kanji: "遅 ", word: " チ オソ.  /  おく.れる おく.らす ", meaning:" slow, late, back, later"},
{kanji: "居 ", word: " キョ コ オ.  /  い.る -い ", meaning:" reside, to be, exist, live with"},
{kanji: "雑 ", word: " ザツ ゾウ  /  まじ.える まじ.る ", meaning:" miscellaneous"},
{kanji: "招 ", word: " ショウ  /  まね.く ", meaning:" beckon, invite, summon, engage"},
{kanji: "困 ", word: " コン  /  こま.る ", meaning:" quandary, become distressed, annoyed"},
{kanji: "欠 ", word: "   /  あくび ", meaning:" lack, gap, fail"},
{kanji: "更 ", word: " コウ  /  さら さら.に ふ.ける ふ.かす ", meaning:" grow late, night watch, sit up late, of course"},
{kanji: "刻 ", word: " コク  /  きざ.む きざ.み ", meaning:" engrave, cut fine, chop, hash, mince, time, carving"},
{kanji: "賛 ", word: " サン  /  たす.ける たた.える ", meaning:" approve, praise, title or inscription on picture, assist, agree with"},
{kanji: "抱 ", word: " ホウ カカ.エ  /  だ.く いだ.く ", meaning:" embrace, hug, hold in arms"},
{kanji: "犯 ", word: " ハン ボン  /  おか.す ", meaning:" crime, sin, offense"},
{kanji: "恐 ", word: " キョウ  /  おそ.れる おそ.る おそ.ろしい こわ.い こわ.がる ", meaning:" fear, dread, awe"},
{kanji: "息 ", word: " ソク  /  いき ", meaning:" breath, respiration, son, interest (on money)"},
{kanji: "遠 ", word: " エン オン トオ.  /   ", meaning:" distant, far"},
{kanji: "戻 ", word: " レイ  /  もど.す もど.る ", meaning:" re-, return, revert, resume, restore, go backwards"},
{kanji: "願 ", word: " ガン -ネガ  /  ねが.う ", meaning:" petition, request, vow, wish, hope"},
{kanji: "絵 ", word: " カイ エ  /   ", meaning:" picture, drawing, painting, sketch"},
{kanji: "越 ", word: " エツ オツ -ゴ.  /  こ.す -こ.す -ご.し こ.える ", meaning:" surpass, cross over, move to, exceed, Vietnam"},
{kanji: "欲 ", word: " ヨク  /  ほっ.する ほ.しい ", meaning:" longing, covetousness, greed, passion, desire, craving"},
{kanji: "痛 ", word: " ツウ  /  いた.い いた.む いた.ましい いた.める ", meaning:" pain, hurt, damage, bruise"},
{kanji: "笑 ", word: " ショウ エ.  /  わら.う ", meaning:" laugh"},
{kanji: "互 ", word: " ゴ  /  たが.い かたみ.に ", meaning:" mutually, reciprocally, together"},
{kanji: "束 ", word: " ソク  /  たば たば.ねる つか つか.ねる ", meaning:" bundle, sheaf, ream, tie in bundles, govern, manage, control"},
{kanji: "似 ", word: " ジ ヒ.  /  に.る ", meaning:" becoming, resemble, counterfeit, imitate, suitable"},
{kanji: "列 ", word: " レツ   /   ", meaning:" file, row, rank, tier, column"},
{kanji: "探 ", word: " タン  /  さぐ.る さが.す ", meaning:" grope, search, look for"},
{kanji: "逃 ", word: " トウ  /  に.げる に.がす のが.す のが.れる ", meaning:" escape, flee, shirk, evade, set free"},
{kanji: "遊 ", word: " ユウ ユ アソ.バ  /  あそ.ぶ ", meaning:" play"},
{kanji: "迷 ", word: " メイ  /  まよ.う ", meaning:" astray, be perplexed, in doubt, lost, err, illusion"},
{kanji: "夢 ", word: " ム ボウ  /  ゆめ ゆめ.みる くら.い ", meaning:" dream, vision, illusion"},
{kanji: "君 ", word: " クン -ギ  /  きみ ", meaning:" old boy, name-suffix"},
{kanji: "閉 ", word: " ヘイ タ.テ  /  と.じる と.ざす し.める し.まる ", meaning:" closed, shut"},
{kanji: "緒 ", word: " ショ チョ イトグ  /  お ", meaning:" thong, beginning, inception, end, cord, strap"},
{kanji: "折 ", word: " セツ オ.レ  /  お.る おり お.り -お.り ", meaning:" fold, break, fracture, bend, yield, submit"},
{kanji: "草 ", word: " ソウ -グ  /  くさ くさ- ", meaning:" grass, weeds, herbs, pasture, write, draft"},
{kanji: "暮 ", word: " ボ ク.ラ  /  く.れる ", meaning:" livelihood, make a living, spend time"},
{kanji: "酒 ", word: " シュ  /  さけ さか ", meaning:" sake, alcohol"},
{kanji: "悲 ", word: " ヒ  /  かな.しい かな.しむ ", meaning:" jail cell, grieve, sad, deplore, regret"},
{kanji: "晴 ", word: " セイ ハ.ラ  /  は.れる は.れ は.れ- -ば.れ ", meaning:" clear up"},
{kanji: "掛 ", word: " カイ ケイ -ガカ  /  か.ける -か.ける か.け -か.け -が.け か.かる -か.かる -が.かる か.かり -が.かり かかり ", meaning:" hang, suspend, depend, arrive at, tax, pour"},
{kanji: "到 ", word: " トウ  /  いた.る ", meaning:" arrival, proceed, reach, attain, result in"},
{kanji: "寝 ", word: " シン  /  ね.る ね.かす い.ぬ みたまや や.める ", meaning:" lie down, sleep, rest, bed, remain unsold"},
{kanji: "暗 ", word: " アン  /  くら.い ", meaning:" darkness, disappear, shade, informal, grow dark, be blinded"},
{kanji: "盗 ", word: " トウ  /  ぬす.む ぬす.み ", meaning:" steal, rob, pilfer"},
{kanji: "吸 ", word: " キュウ  /  す.う ", meaning:" suck, imbibe, inhale, sip"},
{kanji: "陽 ", word: " ヨウ   /   ", meaning:" sunshine, yang principle, positive, male, heaven, daytime"},
{kanji: "御 ", word: " ギョ ゴ  /  おん- お- み ", meaning:" honorable, manipulate, govern"},
{kanji: "歯 ", word: " シ  /  よわい は よわ.い よわい.する ", meaning:" tooth, cog"},
{kanji: "忘 ", word: " ボウ  /  わす.れる ", meaning:" forget"},
{kanji: "雪 ", word: " セツ ユ  /   ", meaning:" snow"},
{kanji: "吹 ", word: " スイ フ.  /   ", meaning:" blow, breathe, puff, emit, smoke"},
{kanji: "娘 ", word: " ジョウ  /  むすめ こ ", meaning:" daughter, girl"},
{kanji: "誤 ", word: " ゴ  /  あやま.る -あやま.る ", meaning:" mistake, err, do wrong, mislead"},
{kanji: "洗 ", word: " セン アラ.  /   ", meaning:" wash, inquire into, probe"},
{kanji: "慣 ", word: " カン  /  な.れる な.らす ", meaning:" accustomed, get used to, become experienced"},
{kanji: "礼 ", word: " レイ ラ  /   ", meaning:" salute, bow, ceremony, thanks, remuneration"},
{kanji: "窓 ", word: " ソウ ス  /  まど てんまど けむだし ", meaning:" window, pane"},
{kanji: "昔 ", word: " セキ シャク  /  むかし ", meaning:" once upon a time, antiquity, old times"},
{kanji: "貧 ", word: " ヒン ビン  /  まず.しい ", meaning:" poverty, poor"},
{kanji: "怒 ", word: " ド ヌ  /  いか.る おこ.る ", meaning:" angry, be offended"},
{kanji: "泳 ", word: " エイ  /  およ.ぐ ", meaning:" swim"},
{kanji: "祖 ", word: "   /   ", meaning:" ancestor, pioneer, founder"},
{kanji: "杯 ", word: " ハイ  /  さかずき ", meaning:" counter for cupfuls, wine glass, glass, toast"},
{kanji: "疲 ", word: " ヒ  /  つか.れる -づか.れ つか.らす ", meaning:" exhausted, tire, weary"},
{kanji: "皆 ", word: " カイ ミン  /  みな ", meaning:" all, everything"},
{kanji: "鳴 ", word: " メイ ナ.ラ  /  な.く な.る ", meaning:" chirp, cry, bark, sound, ring, echo, honk"},
{kanji: "腹 ", word: " フク  /  はら ", meaning:" abdomen, belly, stomach"},
{kanji: "煙 ", word: " エン ケム.  /  けむ.る けむり ", meaning:" smoke"},
{kanji: "眠 ", word: " ミン ネム.  /  ねむ.る ", meaning:" sleep, die, sleepy"},
{kanji: "怖 ", word: " フ ホ  /  こわ.い こわ.がる お.じる おそ.れる ", meaning:" dreadful, be frightened, fearful"},
{kanji: "耳 ", word: " ジ ミ  /   ", meaning:" ear"},
{kanji: "頂 ", word: " チョウ  /  いただ.く いただき ", meaning:" place on the head, receive, top of head, top, summit, peak"},
{kanji: "箱 ", word: " ソウ  /  はこ ", meaning:" box, chest, case, bin, railway car"},
{kanji: "晩 ", word: " バン  /   ", meaning:" nightfall, night"},
{kanji: "寒 ", word: " カン サム.  /   ", meaning:" cold"},
{kanji: "髪 ", word: " ハツ カ  /   ", meaning:" hair of the head"},
{kanji: "忙 ", word: " ボウ モウ  /  いそが.しい せわ.しい おそ.れる うれえるさま ", meaning:" busy, occupied, restless"},
{kanji: "才 ", word: " サイ  /   ", meaning:" genius, years old, cubic shaku"},
{kanji: "靴 ", word: " カ  /  くつ ", meaning:" shoes"},
{kanji: "恥 ", word: " チ  /  は.じる はじ は.じらう は.ずかしい ", meaning:" shame, dishonor"},
{kanji: "偶 ", word: " グウ  /  たま ", meaning:" accidentally, even number, couple, man & wife, same kind"},
{kanji: "偉 ", word: " イ エラ.  /   ", meaning:" admirable, greatness, remarkable, conceited, famous, excellent"},
{kanji: "猫 ", word: " ビョウ  /  ねこ ", meaning:" cat"},
{kanji: "幾 ", word: " キ イク.  /  いく- いく.つ ", meaning:" how many, how much, how far, how long"}
];